<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Event Registration</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="Event registration application">
  <meta name="theme-color" content="#000000">
  
  <link rel="icon" href="/favicon.ico" />

  <link rel="manifest" href="/manifest.json" />

  <link rel="stylesheet" href="%PUBLIC_URL%/index.css">

</head>
<body>
  <div id="root"></div>
  
  <!-- Include your bundled JavaScript file (generated by your build process) -->
  <script src="/static/js/bundle.js"></script>

  <!-- Add any other scripts you need, for example, for analytics or other third-party services -->
  <script src="https://example.com/analytics.js"></script>
</body>
</html>
